Gradient Descent For Neural Network

In [107]:
import numpy as np
import pandas as pd
from tensorflow import keras
import tensorflow as tf

In [108]:
df = pd.read_csv('insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [109]:
df['age'] = df['age']/100

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']], df.bought_insurance, test_size=0.25, random_state=32)

In [111]:
X_train

age  affordibility
18  0.19              0
17  0.58              1
12  0.27              0
8   0.62              1
14  0.49              1
2   0.47              1
15  0.55              1
21  0.26              0
1   0.25              0
26  0.23              1
4   0.46              1
9   0.61              1
10  0.18              1
25  0.54              1
3   0.52              0
7   0.60              0
19  0.18              1
22  0.40              1
5   0.56              1
11  0.28              1
23  0.45              1

In [112]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape = (2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(
    optimizer = 'SGD',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

model.fit(X_train, y_train, epochs = 300)

C:\Users\HT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 572ms/step - accuracy: 0.5714 - loss: 0.6094
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5714 - loss: 0.6090
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5714 - loss: 0.6087
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5714 - loss: 0.6084
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5714 - loss: 0.6081
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5714 - loss: 0.6077
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5714 - loss: 0.6074
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5714 - loss: 0.6071
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5714 - loss: 0.6068
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5714 - loss: 0.6065
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5714 - loss: 0.6062
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5714 - l

In [113]:
y_train

18    0
17    1
12    0
8     1
14    1
2     1
15    1
21    0
1     0
26    0
4     1
9     1
10    0
25    1
3     0
7     1
19    0
22    1
5     1
11    0
23    1
Name: bought_insurance, dtype: int64

In [114]:
model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[0.74281216],
       [0.6851388 ],
       [0.46826258],
       [0.68295324],
       [0.4783458 ],
       [0.5439491 ],
       [0.735009  ]], dtype=float32)

In [115]:
y_test

24    1
0     0
16    1
20    0
13    0
6     0
27    0
Name: bought_insurance, dtype: int64

In [116]:
coef , intercept = model.get_weights()
coef, intercept

(array([[1.0112389],
        [0.9349474]], dtype=float32),
 array([-0.37993023], dtype=float32))

In [117]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [118]:
def prediction_function(age,affordibility):
    wighted_sum =  coef[0]*age+ coef[1]*affordibility + intercept
    return sigmoid(wighted_sum)

In [119]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted = np.clip(y_predicted, epsilon, 1 - epsilon)
    return -np.mean(y_true * np.log(y_predicted) + (1 - y_true) * np.log(1 - y_predicted))

In [120]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))

In [128]:
def gradient_descent(age, affordibility, y_true, epochs):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    
    age = np.array(age)
    affordibility = np.array(affordibility)
    y_true = np.array(y_true)

    
    for i in range(epochs):
        wighted_sum = w1*age +w2*affordibility + bias
        y_predicted = sigmoid((wighted_sum))
        loss = log_loss(y_true,y_predicted)
        
        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))   
        w2d = (1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))   
        
        bias_d = np.mean(y_predicted-y_true)
        
        w1 = w1 - rate*w1d
        w2 = w2 - rate*w2d
        bias = bias - rate*bias_d
        
        print(f'Epoch{i}, w1: {w1}, w2 : {w2}, bias : {bias}, loss: {loss}')
        
        if loss <= 0.5572:
            break
        
    return w1,w2,bias

In [129]:
gradient_descent(X_train['age'], X_train['affordibility'],y_train,5000)

Epoch0, w1: 0.9926396245601022, w2 : 0.9735438700378242, bias : -0.08631487730351776, loss: 0.6093712593662346
Epoch1, w1: 0.9891929044111544, w2 : 0.9537298787096419, bias : -0.16290350673964518, loss: 0.5939971486715504
Epoch2, w1: 0.9892480181735404, w2 : 0.9398799860456002, bias : -0.2307990532976604, loss: 0.5822469867326773
Epoch3, w1: 0.9923735421077637, w2 : 0.9312578610608716, bias : -0.29106952792114715, loss: 0.5732304837358926
Epoch4, w1: 0.9981465047695647, w2 : 0.9271252877895646, bias : -0.3447525300149534, loss: 0.5662229227914245
Epoch5, w1: 1.00617145141959, w2 : 0.9267818985563491, bias : -0.3928118795794959, loss: 0.5606620135453246
Epoch6, w1: 1.0160913574038077, w2 : 0.9295891652041152, bias : -0.4361136320068892, loss: 0.5561276274690188


(np.float64(1.0160913574038077),
 np.float64(0.9295891652041152),
 np.float64(-0.4361136320068892))

In [123]:
coef,intercept

(array([[1.0112389],
        [0.9349474]], dtype=float32),
 array([-0.37993023], dtype=float32))

Implement Neural Network In Python

In [124]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0
    
    def fit(self, X, y, epochs):
        self.gradient_descent(X['age'], X['affordibility'], y,epochs)
    
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid(weighted_sum)
    
    def gradient_descent(self, age, affordibility, y_true, epochs):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        
        age = np.array(age)
        affordibility = np.array(affordibility)
        y_true = np.array(y_true)

        
        for i in range(epochs):
            wighted_sum = w1*age +w2*affordibility + bias
            y_predicted = sigmoid((wighted_sum))
            loss = log_loss(y_true,y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))   
            w2d = (1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))   
            
            bias_d = np.mean(y_predicted-y_true)
            
            w1 = w1 - rate*w1d
            w2 = w2 - rate*w2d
            bias = bias - rate*bias_d
            
            if i%50 == 0:
                print(f'Epoch{i}, w1: {w1}, w2 : {w2}, bias : {bias}, loss: {loss}')
            
            if loss <= 0.5572:
                print(f'Epoch{i}, w1: {w1}, w2 : {w2}, bias : {bias}, loss: {loss}')
                break
        
        return w1,w2,bias
    

In [125]:
customModel = myNN()
customModel.fit(X_train,y_train,100)

Epoch0, w1: 0.9926396245601022, w2 : 0.9735438700378242, bias : -0.08631487730351776, loss: 0.6093712593662346
Epoch6, w1: 1.0160913574038077, w2 : 0.9295891652041152, bias : -0.4361136320068892, loss: 0.5561276274690188


In [130]:
customModel.predict(X_test)

24    0.817574
0     0.772064
16    0.562177
20    0.770299
13    0.571996
6     0.634136
27    0.811533
dtype: float64

In [132]:
model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[0.74281216],
       [0.6851388 ],
       [0.46826258],
       [0.68295324],
       [0.4783458 ],
       [0.5439491 ],
       [0.735009  ]], dtype=float32)